* Header
The International Association for the Properties of Water and Steam

Lucerne, Switzerland August 2007

Revised Release on the IAPWS Industrial Formulation 1997
for the Thermodynamic Properties of Water and Steam
(The revision only relates to the extension of region 5 to 50 MPa)

2007 International Association for the Properties of Water and Steam
Publication in whole or in part is allowed in all countries provided that attribution is given to the
International Association for the Properties of Water and Steam

President:
J. R. Cooper
School of Engineering and Materials Science
Queen Mary, University of London
Mile End Road
London E1 4NS, England
Executive Secretary:
Dr. R. B. Dooley
Structural Integrity Associates, Inc.
2616 Chelsea Drive
Charlotte, NC 28209, USA
email: bdooley@structint.com

This revised release replaces the corresponding release of 1997 and contains 49 pages, including this
cover page.

This release has been authorized by the International Association for the Properties of Water and
Steam (IAPWS) at its meeting in Lucerne, Switzerland, 26-31 August, 2007, for issue by its
Secretariat. The members of IAPWS are: Argentina and Brazil, Britain and Ireland, Canada, the Czech
Republic, Denmark, France, Germany, Greece, Italy, Japan, Russia, and the United States of America,
and associate member Switzerland.

The formulation provided in this release is recommended for industrial use, and is called "IAPWS
Industrial Formulation 1997 for the Thermodynamic Properties of Water and Steam" abbreviated to
"IAPWS Industrial Formulation 1997" (IAPWS-IF97). The IAPWS-IF97 replaces the previous
Industrial formulation "The 1967 IFC Formulation for Industrial Use" (IFC-67) [1]. Further details
about the formulation can be found in the article by W. Wagner et al. [2] and for the extended region 5
in [2a]. Additional supplementary backward equations have been adopted by IAPWS and are listed in
[2b].

The material contained in this release is identical to that contained in the release on IAPWS-IF97,
issued by IAPWS in September 1997, except for the basic equation for region 5. The previous basic
equation for this region was replaced by a new equation of the same structure. For temperatures
between 1073 K and 2273 K, this equation extends the upper range of validity of IAPWS-IF97 in
pressure from 10 MPa to 50 MPa. Except for the basic equation for region 5 of IAPWS-IF97, the
property calculations are unchanged.

In addition, minor editorial changes to this document, involving correction of typographical errors
and updating of references, were made in the 2007 revision, and again in 2009 and 2010. In 2012, the
description of the range of validity of the equation for the metastable vapor was clarified.

IAPWS also has a formulation intended for general and scientific use [3].

Further information about this release and other releases issued by IAPWS can be obtained from
the Executive Secretary of IAPWS or from http://www.iapws.org.

* Nomenclature

Thermodynamic quantities:

| c_p | Specific isobaric heat capacity               |
| c_v | Specific isochoric heat capacity              |
| f   | Specific Helmholtz free energy                |
| g   | Specific Gibbs free energy                    |
| h   | Specific enthalpy                             |
| M   | Molar mass                                    |
| p   | Pressure                                      |
| R   | Specific gas constant                         |
| R_m | Molar gas constant                            |
| s   | Specific entropy                              |
| T   | Absolute temperature^a                        |
| u   | Specific internal energy                      |
| v   | Specific volume                               |
| w   | Speed of sound                                |
| x   | General quantity                              |
| β   | Transformed pressure, Eq. (29a)               |
| γ   | Dimensionless Gibbs free energy, γ=g/(RT)     |
| δ   | Reduced density, δ=ρ/ρ^*                      |
| Δ   | Difference in any quantity                    |
| η   | Reduced enthalpy, η=h/h^*                     |
| θ   | Reduced temperature, θ=T/T^*                  |
| υ   | Transformed temperature, Eq. (29b)            |
| π   | Reduced pressure, π=ρ/ρ^*                     |
| ρ   | Mass density                                  |
| σ   | Reduced entropy, σ=s/s*                       |
| τ   | Inverse reduced temperature, τ=T^*/T          |
| φ   | Dimensionless Helmholtz free energy, φ=f/(RT) |

Superscripts:

| o | Ideal-gas part         |
| r | Residual part          |
| * | Reducing quantity      |
| ' | Saturated liquid state |
| " | Saturated vapor state  |

Subscripts:

| c   | Critical point          |
| max | Maximum value           |
| RMS | Root-mean-square value  |
| s   | Saturation state        |
| t   | Triple point            |
| tol | Tolerance of a quantity |

Root-mean-square deviation:

Δx_{RMS}=sqrt(/1 N(summ 1 N (Δx_n)^2))

where Δxn can be either absolute
or percentage difference between
the corresponding quantities x; N
is the number of Δxn values
(depending on the property,
between 10 million and 100
million points are uniformly
distributed over the respective
range of validity).

* Structure of the Formulation
The IAPWS Industrial Formulation 1997 consists of a set of equations for different regions
which cover the following range of validity:

| 273.15 K <= T <= 1073.15 K  | p <= 100 MPa |
| 1073.15 K <= T <= 2273.15 K | p <= 50 MPa. |

Figure 1 shows the five regions into which the entire range of validity of IAPWS-IF97 is
divided. The boundaries of the regions can be directly taken from Fig. 1 except for the
boundary between regions 2 and 3; this boundary is defined by the so-called B23-equation
given in Section 4. Both regions 1 and 2 are individually covered by a fundamental equation
for the specific Gibbs free energy g(p, T), region 3 by a fundamental equation for the specific
Helmholtz free energy f (ρ, T), where ρ is the density, and the saturation curve by a
saturation-pressure equation ps(T). The high-temperature region 5 is also covered by a g(p, T)
equation. These five equations, shown in rectangular boxes in Fig. 1, form the so-called basic
equations.

[[./IAPWS_R7-97(2012)_Fig_1.png]]

Regarding the main properties specific volume v, specific enthalpy h, specific isobaric heat 
capacity c_p, speed of sound w, and saturation pressure p_s, the basic equations represent 
the corresponding values from the "IAPWS Formulation 1995 for the Thermodynamic 
Properties of Ordinary Water Substance for General and Scientific Use" [3] (hereafter 
abbreviated to IAPWS-95) to within the tolerances specified for the development of 
the corresponding equations; details of these requirements and their fulfillment are 
given in the comprehensive paper on IAPWS-IF97 [2]. The basic equations for 
regions 1 and 3 also yield reasonable values for the metastable states close to the 
stable regions. For region 2 there is a special equation for the metastable-vapor region. 
Along the region boundaries the corresponding basic equations are consistent with each 
other within specified tolerances; for details see Section 10. 

In addition to the basic equations, for regions 1, 2, and 4 so-called backward equations 
are provided in the forms of T ( p,h ) and T ( p,s ) for regions 1 and 2, and Ts ( p ) for 
region 4. These backward equations are numerically consistent with the corresponding 
basic equations and make the calculation of properties as functions of  p,h and of  p,s 
for regions 1 and 2, and of p for region 4, extremely fast. In this way, properties such 
as T ( p,h ), h ( p,s ), and h_s( p ) can be calculated without any iteration from the backward
 equation alone or by combination with the corresponding basic equation, for example, 
h ( p,s ) via the relation h ( p,T ( p,s )). As a consequence, the calculation of the industrially
 most important properties is on average more than five times faster than the corresponding
 calculation with IFC-67; for details see Section 11. 


* Reference Constants

* Auxiliary Equation for the Boundary between Regions 2 and 3

* Equations for Region 1

** Basic Equation
** Backward Equations
*** The Backward Equation T (p,h)
*** The Backward Equation T (p,s)

* Equations for Region 2
This section contains all details relevant for the use of the basic and backward equations of
region 2 of IAPWS-IF97. Information about the consistency of the basic equation of this
region with the basic equations of regions 3, 4 and 5 along the corresponding region
boundaries is summarized in Section 10. The auxiliary equation for defining the boundary
between regions 2 and 3 is given in Section 4. Section 11 contains the results of computingtime
comparisons between IAPWS-IF97 and IFC-67. The estimates of uncertainty of the most
relevant properties can be found in Section 12.

** Basic Equation
The basic equation for this region is a fundamental equation for the specific Gibbs free
energy g. This equation is expressed in dimensionless form, γ = g/( RT ), and is separated into
two parts, an ideal-gas part γ^o and a residual part γ^r, so that

  FORMULA (15)

where π = p/p* and τ= T^*/T with R given by Eq. (1).


** Supplementary Equation for the Metastable-Vapor Region
** Backward Equations
*** The Backward Equations T( p,h ) for Subregions 2a, 2b, and 2c
*** The Backward Equations T( p,s ) for Subregions 2a, 2b, and 2c

* Basic Equation for Region 3

* Equations for Region 4
** The Saturation-Pressure Equation (Basic Equation)
** The Saturation-Temperature Equation (Backward Equation)

* Basic Equation for Region 5

* Consistency at Region Boundaries
** Consistency at Boundaries between Single-Phase Regions
** Consistency at the Saturation Line

* Computing Time of IAPWS-IF97 in Relation to IFC-67
** Computing-Time Investigations for Regions 1, 2, and 4
** Computing-Time Investigations for Region 3

* Estimates of Uncertainties
* References 49
